### PR TITLE
Fix: Rectify ffmpy poetry config; update version from 0.3.2 to 0.4.0

### PR DESCRIPTION
**Pull request by arturmartins**
# Description

The current `poetry install` is broken for first installers:
Screenshot 2024-08-18 at 13 56 50

The reason:
- https://github.com/EuDs63/ffmpy is no longer the source repo of ffmpy (archived on 30 July 2024)
Screenshot 2024-08-18 at 13 58 45
No tags available

If you visit https://pypi.org/project/ffmpy/#history, you can see that it points to a new repo: https://github.com/Ch00k/ffmpy

Related Issues:
- https://github.com/zylon-ai/private-gpt/issues/1378
- https://github.com/zylon-ai/private-gpt/issues/1738
- https://github.com/zylon-ai/private-gpt/issues/1795
- https://github.com/zylon-ai/private-gpt/issues/2005
- https://github.com/zylon-ai/private-gpt/issues/2023

## Type of Change

- [x ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I ran the command `poetry add ffmpy@0.3.2`, and poetry installed all packages without any problem.

``` 
Updating dependencies
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/c7/2c/94ed7b91db81d61d7096ac8f2d325ec562fc75e35f3baea8
Resolving dependencies... (32.9s)

Package operations: 97 installs, 2 updates, 0 removals

  - Downgrading cffi (1.17.0 -> 1.16.0)
  - Installing h11 (0.14.0)
  - Installing mdurl (0.1.2)
  - Installing sniffio (1.3.1)
  - Installing typing-extensions (4.12.2)
  - Installing wrapt (1.16.0)
  - Installing annotated-types (0.7.0)
  - Installing anyio (4.4.0)
  - Installing cryptography (3.4.8)
  - Installing deprecated (1.2.14)
  - Installing frozenlist (1.4.1)
  - Installing httpcore (1.0.5)
  - Installing markdown-it-py (3.0.0)
  - Installing multidict (6.0.5)
  - Installing mypy-extensions (1.0.0)
  - Installing pydantic-core (2.20.1)
  - Installing pygments (2.18.0)
  - Installing six (1.16.0)
  - Installing aiosignal (1.3.1)
  - Installing attrs (23.2.0)
  - Installing click (8.1.7)
  - Installing distro (1.9.0)
  - Installing fsspec (2024.6.1)
  - Installing greenlet (3.0.3)
  - Installing httpx (0.27.0)
  - Installing joblib (1.4.2)
  - Installing marshmallow (3.21.3)
  - Installing numpy (1.26.4)
  - Installing pydantic (2.8.2)
  - Installing python-dateutil (2.9.0.post0)
  - Installing pytz (2024.1)
  - Installing pyyaml (6.0.1)
  - Installing regex (2024.7.24)
  - Installing rich (13.7.1)
  - Installing tqdm (4.66.4)
  - Installing typing-inspect (0.9.0)
  - Installing tzdata (2024.1)
  - Installing yarl (1.9.4)
  - Installing aiohttp (3.9.5)
  - Installing dataclasses-json (0.6.7)
  - Installing dirtyjson (1.0.8)
  - Installing dnspython (2.6.1)
  - Installing httptools (0.6.1)
  - Installing huggingface-hub (0.24.3)
  - Installing markupsafe (2.1.5)
  - Installing nest-asyncio (1.6.0)
  - Installing networkx (3.3)
  - Installing nltk (3.8.1)
  - Installing openai (1.37.1)
  - Installing pandas (2.2.2)
  - Installing pillow (10.4.0)
  - Installing python-dotenv (1.0.1)
  - Installing sqlalchemy (2.0.31)
  - Installing tenacity (8.5.0)
  - Installing tiktoken (0.7.0)
  - Installing typer (0.12.3)
  - Installing uvloop (0.19.0)
  - Installing watchfiles (0.22.0)
  - Installing websockets (11.0.3)
  - Installing email-validator (2.2.0)
  - Installing fastapi-cli (0.0.4)
  - Installing jinja2 (3.1.4)
  - Installing llama-index-core (0.10.58)
  - Installing python-multipart (0.0.9)
  - Installing safetensors (0.4.3)
  - Installing starlette (0.37.2)
  - Installing tokenizers (0.19.1)
  - Installing uvicorn (0.30.3)
  - Installing fastapi (0.111.1)
  - Installing iniconfig (2.0.0)
  - Installing orjson (3.10.6)
  - Installing pluggy (1.5.0)
  - Installing soupsieve (2.5)
  - Installing transformers (4.43.3)
  - Installing ujson (5.10.0)
  - Installing beautifulsoup4 (4.12.3)
  - Installing cfgv (3.4.0)
  - Installing coverage (7.6.0)
  - Updating ffmpy (0.3.1 -> 0.4.0)
  - Installing identify (2.6.0)
  - Installing itsdangerous (2.2.0)
  - Installing nodeenv (1.9.1)
  - Installing pathspec (0.12.1)
  - Installing pydantic-extra-types (2.9.0)
  - Installing pydantic-settings (2.3.4)
  - Installing pypdf (4.3.1)
  - Installing pytest (7.4.4)
  - Installing ruff (0.5.5)
  - Installing striprtf (0.0.26)
  - Installing black (22.12.0)
  - Installing docx2txt (0.8)
  - Installing injector (0.21.0)
  - Installing llama-index-readers-file (0.1.31)
  - Installing mypy (1.11.0)
  - Installing pre-commit (2.21.0)
  - Installing pytest-asyncio (0.21.2)
  - Installing pytest-cov (3.0.0)
  - Installing types-pyyaml (6.0.12.20240724)
  - Installing watchdog (4.0.1)

Writing lock file
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I ran `make check; make test` to ensure mypy and tests pass
Screenshot 2024-08-18 at 14 31 15

### CODE REVIEW

**Comment by arturmartins** [comment]
Message for the maintainers @jaluma, @imartinez:

I also tested for version 0.4.0 which worked fine. Version 0.4.0 has some improvements and also adopted poetry: https://github.com/Ch00k/ffmpy/compare/0.3.2...0.4.0

I would be happy to update this PR to use 0.4.0 instead if there is a path forward for testing the version update. Or this PR gets merged and after I create a new PR to include version 0.4.0.  

Looking forward to hearing from you.
Artur

**Comment by jaluma** [comment]
> Message for the maintainers @jaluma, @imartinez:
> 
> I also tested for version 0.4.0 which worked fine. Version 0.4.0 has some improvements and also adopted poetry: [Ch00k/ffmpy@0.3.2...0.4.0](https://github.com/Ch00k/ffmpy/compare/0.3.2...0.4.0)
> 
> I would be happy to update this PR to use 0.4.0 instead if there is a path forward for testing the version update. Or this PR gets merged and after I create a new PR to include version 0.4.0.
> 
> Looking forward to hearing from you. Artur

Feel free to do so. Thanks you :)

**Comment by arturmartins** [comment]
@jaluma: Updated it to 0.4.0  https://github.com/zylon-ai/private-gpt/pull/2062/commits/d38170034aa8578e56b9fbabe60a923d59a4379c

**Review by jaluma — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
